# Generated by Django 3.1 on 2020-08-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesweb', '0008_message_readed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='readed',
        ),
    ]
