# Generated by Django 3.1 on 2020-09-08 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moviesweb', '0010_message_readed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sended',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
